### ISSUE TITLE
Unable to compile using OpenTracing 1.6.0

### ISSUE THREAD

**Issue by LewisRye** [opentracing/lua-bridge-tracer#16]
```
[ 87%] Building CXX object CMakeFiles/opentracing_bridge_tracer.dir/src/module.cpp.o
/tmp/lua-bridge-tracer/src/dynamic_tracer.cpp: In member function 'virtual std::unique_ptr<opentracing::v3::Span> lua_bridge_tracer::{anonymous}::DynamicTracer::StartSpanWithOptions(opentracing::v3::string_view, const opentracing::v3::StartSpanOptions&) const':
/tmp/lua-bridge-tracer/src/dynamic_tracer.cpp:122:75: error: invalid new-expression of abstract class type 'lua_bridge_tracer::{anonymous}::DynamicSpan'
122 | new (std::nothrow) DynamicSpan(shared_from_this(), std::move(span))};
| ^
```
OpenTracing 1.6.0 seems to have a value that this repository doesn't like?
